### ISSUE TITLE
Right / Left meaning

### ISSUE THREAD

**Issue by DoNck** [ashtuchkin/vive-diy-position-sensor#20]
Hi,

I am pretty confused reading your explanation in the wiki: [step-2-calculate-3d-planes-from-stations](https://github.com/ashtuchkin/vive-diy-position-sensor/wiki/Position-calculation-in-detail#step-2-calculate-3d-planes-from-stations).
I feel like the text and drawing are not coherent regarding the x axis:
![xyz drawxing](https://cloud.githubusercontent.com/assets/627997/20653622/4149c188-b4c5-11e6-8346-c06b378ccb2b.png)
You wrote ***"X is left"*** but when I look at your drawing, ***I see X going to the right***.
***Is there something wrong in your text/drawing or did I missunderstand what you actually meant by "left" ?***
  

This goes out of the scope of this project, but left/side terms are actually pretty unclear to me in a lot of vive lighthouse related discussions as people may use different point of views:
- looking at the face of lighthouse
- looking at the environment from the lighthouse point of view
- looking at 2D axis of a picture showing a lighthouse system

I think something we all agree on is the naming of a faces on a cube:
![faces name on a cube](http://images.algebraden.com/geometry/cube-4.jpg)
I think using this vocabulary could ease discussions and reading/writing documentation.

**Comment by ashtuchkin** [comment]
I meant "X is going right-to-left from the point of view of base station", i.e. when you look in the direction of inverse Z ("Station looks here" on the pic). Specifically, at the center X=0, then negative values to the right and positive to the left.

I agree it's confusing. Not sure what to do though, as naming the faces of the cube doesn't make it clear to me, because you also need to specify the rotation of the cube, right?
