### ISSUE TITLE
How to send the sensor-timing measurements in good way?

### ISSUE THREAD

**Issue by GameFaceLabs** [ashtuchkin/vive-diy-position-sensor#28]
All timing-values always (no matter having gotten a trigger or not)?
Only triggered channels/sensors (e.g. filtering which is to be sent over to Unity).
Only max of xx sensors? (xx then decided upon by some criteria...)

**Comment by ashtuchkin** [comment]
Not sure what trigger you mean here, could you write full questions please?

Max number of sensors depends on the microcontroller in use and method of
capturing pulses. Currently a teensy can serve 3 sensors using comparator
method, plus 6 more using hardware timers (in works now). Photon can serve
6 sensors if I remember correctly.

On May 22, 2017 12:07 PM, "GameFaceLabs" <notifications@github.com> wrote:

All timing-values always (no matter having gotten a trigger or not)?
Only triggered channels/sensors (e.g. filtering which is to be sent over to
Unity).
Only max of xx sensors? (xx then decided upon by some criteria...)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ashtuchkin/vive-diy-position-sensor/issues/28>, or mute
the thread
